### ISSUE TITLE
Filtrer les citation par auteur

### ISSUE THREAD

**Issue by ZirconiumZr40** [MPSI1Thuillier/Bot#11]
Je propose d'intégrer à la commande .citation un filtre par rapport aux auteurs :
Celui permettrait d'avoir des citations d'un seul auteur (par exemple avec un ".citation VVK" on obtient obligatoirement une citation de VVK).

**Comment by NathanFallet** [comment]
@H2WO4 Implementer cette feature va demander d'adapter le système de random que tu as fait : en temps normal il faut juste filter la liste par auteur et return un élément random, mais là ça ne marche pas pareil

**Comment by H2WO4** [comment]
Normalement, je peux le faire facilement en créant une nouvelle liste avec que les citations de VVK par exemple.
Il faudra juste que je repasse à des poids normaux plutôt que cumulatifs.
