### ISSUE TITLE
Sound and music command

### ISSUE THREAD

**Issue by ZirconiumZr40** [MPSI1Thuillier/Bot#22]
Je pense que l'on pourrais faire une commande qui réunit ".audio" et ".music", c'est a dire qu'avec un ".music" je bot rejoint le channel et se met a jouer la musique

Voilà :)

**Comment by NathanFallet** [comment]
Pourquoi pas, et en même temps j'en profiterai pour ajouter la suppression des messages lors de ces commandes là

**Comment by NathanFallet** [comment]
Je garde quand même la commande .audio car elle permet de move le bot sans relancer de musique
